all: calc

calc: Driver.cpp Expression.cpp
	g++ Driver.o Expression.o -o calc

Driver.o: Driver.cpp
	g++ -c Driver.cpp

Expression.o: Expression.cpp
	g++ -c Expression.cpp

clean:
	rm -rf *o calc